local modname = "__kj_stargate__"
data:extend({
	{
		type = "sound",
		name = "kj_stargate_open",
		filename = modname.."/sounds/gate_open.ogg",
		volume = 1,
		category = "environment",
		audible_distance_modifier = 1,
	},
	{
		type = "sound",
		name = "kj_stargate_close",
		filename = modname.."/sounds/gate_close.ogg",
		volume = 1,
		category = "environment",
		audible_distance_modifier = 1,
	},
	{
		type = "sound",
		name = "kj_stargate_fail",
		filename = modname.."/sounds/gate_fail.ogg",
		volume = 1,
		category = "environment",
		audible_distance_modifier = 1,
	},
	{
		type = "sound",
		name = "kj_stargate_enter",
		filename = modname.."/sounds/gate_enter.ogg",
		volume = 1,
		category = "environment",
		audible_distance_modifier = 1,
	},
	{
		type = "sound",
		name = "kj_stargate_openIdle",
		filename = modname.."/sounds/gate_puddle.ogg",
		volume = 1,
		category = "environment",
		audible_distance_modifier = 1,
	},
})

data:extend({
	{
		type = "sound",
		name = "kj_stargate_chevron1",
		filename = modname.."/sounds/chevron_open1.ogg",
		volume = 1,
		category = "environment",
		audible_distance_modifier = 1,
	},
	{
		type = "sound",
		name = "kj_stargate_chevron2",
		filename = modname.."/sounds/chevron_open2.ogg",
		volume = 1,
		category = "environment",
		audible_distance_modifier = 1,
	},
	{
		type = "sound",
		name = "kj_stargate_chevron3",
		filename = modname.."/sounds/chevron_open3.ogg",
		volume = 1,
		category = "environment",
		audible_distance_modifier = 1,
	},

	{
		type = "sound",
		name = "kj_stargate_dhd1",
		filename = modname.."/sounds/dhd_1.ogg",
		volume = 1,
		category = "environment",
		audible_distance_modifier = 1,
	},
	{
		type = "sound",
		name = "kj_stargate_dhd2",
		filename = modname.."/sounds/dhd_2.ogg",
		volume = 1,
		category = "environment",
		audible_distance_modifier = 1,
	},
	{
		type = "sound",
		name = "kj_stargate_dhd3",
		filename = modname.."/sounds/dhd_3.ogg",
		volume = 1,
		category = "environment",
		audible_distance_modifier = 1,
	},
	{
		type = "sound",
		name = "kj_stargate_dhd4",
		filename = modname.."/sounds/dhd_4.ogg",
		volume = 1,
		category = "environment",
		audible_distance_modifier = 1,
	},
	{
		type = "sound",
		name = "kj_stargate_dhd5",
		filename = modname.."/sounds/dhd_5.ogg",
		volume = 1,
		category = "environment",
		audible_distance_modifier = 1,
	},
	{
		type = "sound",
		name = "kj_stargate_dhd6",
		filename = modname.."/sounds/dhd_6.ogg",
		volume = 1,
		category = "environment",
		audible_distance_modifier = 1,
	},
	{
		type = "sound",
		name = "kj_stargate_dhd7",
		filename = modname.."/sounds/dhd_7.ogg",
		volume = 1,
		category = "environment",
		audible_distance_modifier = 1,
	},
	{
		type = "sound",
		name = "kj_stargate_dhdc",
		filename = modname.."/sounds/dhd_c.ogg",
		volume = 1,
		category = "environment",
		audible_distance_modifier = 1,
	},
})